apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: second
  labels:
    app: hello-mini
spec:
  type: NodePort
  selector:
    app: hello-mini
  ports:
  - name: open
    port: 8888
    nodePort: 31121
    protocol: TCP
    targetPort: open
